# Dockerfile
FROM golang:1.17.6-alpine3.15
 
WORKDIR /app
RUN go get github.com/cosmtrek/air
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build cmd/main.go 

ENTRYPOINT ["air", "-c", "air.toml"]