# Dockerfile
FROM golang:1.18.3-alpine3.16 
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go install github.com/githubnemo/CompileDaemon@latest # for hot reload
COPY . .

ENTRYPOINT CompileDaemon --build="go build -o ./bin/main ./cmd/main.go"  --command=./bin/main
