# Dockerfile
FROM golang:1.18.3-alpine3.16 
WORKDIR /app
RUN go install github.com/cosmtrek/air@latest
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build cmd/main.go

ENTRYPOINT ["air", "-c", "air.toml"]
